database_connection: # WARNING: DO NOT USE YOUR LIVE PRODUCTION DATABASE
  user: postgres
  password: postgres
  host: localhost
  port: 5432
  database_name: test_database
transformations:
  # Supported values for transform mode keys: first-name | full-name | email | random | phone-number | number | address | address2 | token
  # Supported values for mask mode keys: email | first-name | full-name | phone-number | token | random
  - table: comments
    columns:
      - name: comment_text
        mode: transform
        mode_key: random
  - table: customer_log
    columns:
      - name: march_code
        mode: transform
        mode_key: random
      - name: email
        mode: mask
        mode_key: email
      - name: token
        mode: mask
        mode_key: token
  - table: customerdetails
    columns:
      - name: full_name
        mode: transform
        mode_key: full-name
      - name: address1
        mode: transform
        mode_key: address
      - name: address2
        mode: transform
        mode_key: address2
      - name: phone
        mode: transform
        mode_key: phone-number
  - table: ncustomer
    columns:
      - name: email
        mode: transform
        mode_key: email
      - name: token
        mode: mask
        mode_key: token
      - name: march_code
        mode: transform
        mode_key: random
  - table: paymentdetails
    columns:
      - name: billing_ref
        mode: mask
        mode_key: random
      - name: bank_ref
        mode: mask
        mode_key: random
  - table: paymentmethods
    columns:
      - name: payment_id
        mode: mask
        mode_key: random
      - name: payment_gateway_cust_id
        mode: mask
        mode_key: random
  - table: seller
    columns:
      - name: address1
        mode: mask
        mode_key: random
      - name: address2
        mode: mask
        mode_key: random
      - name: tax_id_number
        mode: mask
        mode_key: random
      - name: email
        mode: mask
        mode_key: email
  - table: supplier
    columns:
      - name: address1
        mode: mask
        mode_key: random
      - name: address2
        mode: mask
        mode_key: random
      - name: phone
        mode: mask
        mode_key: random
      - name: email
        mode: mask
        mode_key: email
database_subset:
  percentage: 10
  subset_tables:
    - comments
    - in_pincode
    - order_log
    - product_log
    - uk_pincode
