database_connection:
  user: postgres
  password: postgres
  host: localhost
  port: 5432
  database_name: test_database
transformations: # Supported values for transformer: first-name | full-name | email | random | phone-number | number
  - table: adminuser
    columns:
      - name: first_name
        transform_key: full-name
      - name: email
        transform_key: email
      - name: password
        transform_key: random
database_subset:
  sample_percentage: 10
  subset_tables: # Supported values: comments | in_pincode | order_log | product_log | uk_pincode
    - comments
    - in_pincode
    - order_log
    - product_log
    - uk_pincode
