database_connection: # WARNING: DO NOT USE YOUR LIVE PRODUCTION DATABASE
  user: postgres
  password: postgres
  host: localhost
  port: 5432
  database_name: test_stage
transformations:
  # Supported values for transform mode keys: first-name | full-name | email | random | phone-number | number | address | address2 | token
  # Supported values for mask mode keys: email | first-name | full-name | phone-number | token | random
  - table: order
    columns:
      - name: notes
        mode: transform
        mode_key: random
  - table: comments
    columns:
      - name: comment_text
        mode: transform
        mode_key: random
  - table: customer_log
    columns:
      - name: march_code
        mode: transform
        mode_key: random
      - name: email
        mode: transform
        mode_key: email
  - table: customerdetails
    columns:
      - name: full_name
        mode: transform
        mode_key: full-name
      - name: address1
        mode: transform
        mode_key: address
      - name: address2
        mode: transform
        mode_key: address2
      - name: phone
        mode: transform
        mode_key: phone-number
  - table: ncustomer
    columns:
      - name: email
        mode: transform
        mode_key: email
      - name: referral_code
        mode: transform
        mode_key: random-free
      - name: march_code
        mode: transform
        mode_key: random
  - table: paymentmethods
    columns:
      - name: payment_id
        mode: mask
        mode_key: random
  - table: supplier
    columns:
      - name: name
        mode: transform
        mode_key: random
      - name: short_name
        mode: transform
        mode_key: random
      - name: address1
        mode: mask
        mode_key: random
      - name: address2
        mode: mask
        mode_key: random
      - name: phone
        mode: mask
        mode_key: random
      - name: email
        mode: transform
        mode_key: email
  - table: order
    columns:
      - name: notes
        mode: transform
        mode_key: random
database_subset:
  percentage: 10
  subset_tables: # Supported values: comments | in_pincode | order_log | product_log | uk_pincode
    - comments
    - in_pincode
    - order_log
    - product_log
    - uk_pincode
